version: '3.8'

services:
  db:
    image: postgres:15
    env_file: .env.prod
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: fastapi-ecom-backend:latest
    env_file: .env.prod
    command: gunicorn --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 main:app --access-logfile /tmp/log.txt
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./:/app
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: fastapi-ecom-backend:latest
    command: celery -A worker.celery_app worker -I tasks --loglevel=info
    env_file: .env.prod
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./:/app
    networks:
      - app-network
    restart: unless-stopped

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: fastapi-ecom-backend:latest
    command: alembic upgrade head
    env_file: .env.prod
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: "no"

volumes:
  db_data:
  redis_data:

networks:
  app-network:
    driver: bridge

